include: package:flutter_lints/flutter.yaml

analyzer:
  plugins:
    - custom_lint
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"
    - "backend/**"
    - "build/**"
    - "lib/generated_plugin_registrant.dart"
    - "lib/l10n/**"
    - "lib/gen/**"
    - "test_driver/**"
    - "web/**"
    - "node_modules/**"
    - "scripts/**"
  language:
    strict-casts: false
    strict-inference: false
    strict-raw-types: false
  errors:
    avoid_web_libraries_in_flutter: ignore
    dead_code: info
    deprecated_member_use_from_same_package: ignore
    included_file_warning: ignore
    invalid_annotation_target: ignore
    invalid_assignment: warning
    missing_required_param: error
    missing_return: error
    parameter_assignments: warning
    unused_import: warning
    camel_case_types: ignore
    constant_identifier_names: ignore
    file_names: ignore
    implementation_imports: ignore
    non_constant_identifier_names: ignore
    overridden_fields: ignore
    prefer_void_to_null: ignore
    todo: ignore

linter:
  rules:
    - always_declare_return_types: true
    - avoid_print: true
    - unrelated_type_equality_checks: true
    - unsafe_html: true
    - use_super_parameters: true
    - valid_regexps: true
    - undefined_prefix_name: false
    - avoid_web_libraries_in_flutter: false
