name: client
description: "Nvidia GenAI Agents Developer Contest."
publish_to: "none"
version: 0.0.1+alpha.0
environment:
  sdk: ">=3.4.3 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_secure_storage: ^4.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  build_web_compilers: ^4.0.10
  custom_lint: ^0.6.4
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
